version: '3.1'

services:
  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_NAME}"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tgbot:
    build:
      context: .
    restart: always
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      ADMIN_ID: "${ADMIN_ID}"
      TELEGRAM_PROXY: "${TELEGRAM_PROXY}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: 5432
      DB_HOST: db